
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.9.6.  DO NOT EDIT!
//*************************************************************************************

using System;
using XTC.FMP.MOD.Hotspot2D.LIB.Bridge;

namespace XTC.FMP.MOD.Hotspot2D.LIB.Unity
{
    public class DesignerUiBridgeBase : IDesignerUiBridge
    {
        public virtual void Alert(string _code, string _message)
        {
            throw new NotImplementedException();
        }


        public virtual void RefreshReadStyleSheet(IDTO _dto)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshWriteStyle(IDTO _dto)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshReadInstances(IDTO _dto)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshWriteInstances(IDTO _dto)
        {
            throw new NotImplementedException();
        }

    }
}
