
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.9.1.  DO NOT EDIT!
//*************************************************************************************

using System;
using XTC.FMP.MOD.Hotspot2D.LIB.Bridge;

namespace XTC.FMP.MOD.Hotspot2D.LIB.Unity
{
    public class HealthyUiBridgeBase : IHealthyUiBridge
    {
        public virtual void Alert(string _code, string _message)
        {
            throw new NotImplementedException();
        }


        public virtual void RefreshEcho(IDTO _dto)
        {
            throw new NotImplementedException();
        }

    }
}
