
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.9.1.  DO NOT EDIT!
//*************************************************************************************

using System.Xml.Serialization;

namespace XTC.FMP.MOD.Hotspot2D.LIB.Unity
{
    public class MyConfigBase
    {
        public class GRPC
        {
            [XmlAttribute("address")]
            public string address { get; set; } = "";
        }

        public class UI
        {
            [XmlAttribute("visible")]
            public bool visible { get; set; } = false;

            [XmlAttribute("slot")]
            public string slot { get; set; } = "[root]";
        }

        public class Instance
        {
            [XmlAttribute("uid")]
            public string uid { get; set; } = "";
            [XmlAttribute("style")]
            public string style { get; set; } = "";
        }

        [XmlAttribute("version")]
        public string version { get; set; } = "";

        [XmlElement("GRPC")]
        public GRPC grpc { get; set; } = new GRPC();

        [XmlElement("UI")]
        public UI ui { get; set; } = new UI();

        [XmlArray("Instances"), XmlArrayItem("Instance")]
        public Instance[] instances { get; set; } = new Instance[0];
    }

}

